@startuml
Class Humano
Class Estado
class Foco{
    -Estado estado
    +Encender()
    +Apagar()
    +Estado : MostrarEstado()
}

Class SerieNavidad{
    - Foco focos[10]
    +Encender()
    +Apagar()
    +ImprimirSerie()
}

Humano o-- Foco
Foco *-- Estado
Estado --|> bool
SerieNavidad "1" *-- "10" Foco 
Humano o-- SerieNavidad

@enduml